### ISSUE TITLE
依赖问题

### ISSUE THREAD

**Issue by SENyiAi** [ClankySun10936/Phigros-Autoplay-Script#1]
我差不多安了10G依赖都没能跑起你的程序
lz4==3.1.10要求安装8个G的vs
numpy==1.21.4没对应版本
Pillow==9.0.1报错lambda: warnings.warn( error: legacy-install-failure
换了版本就提示缺失依赖不让运行，能不能改进一下
python是3.11.1

**Comment by sceatcher3** [comment]
原作phisap有句原话（请安装Python 3.10。真的很重要，因为项目使用了一些3.10才支持的语法糖，并且我不打算做向下兼容）
这个改编没写出来
