### ISSUE TITLE
解包报错

### ISSUE THREAD

**Issue by Cicada000** [ClankySun10936/Phigros-Autoplay-Script#2]
解包时出现报错：
![image](https://user-images.githubusercontent.com/78632923/229288855-1e60df85-f994-43d7-8106-e5f40af18985.png)

电脑：Windows11 25330
APK：2.5.1（2023愚人节版）

**Comment by d-i-amond** [comment]
一样的版本，也是解包报错，但是报错内容不同
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Release.1.0.0\main.py", line 448, in <module>
    App(Tk()).load_songs().load_cache('./cache').mainloop()
    
  File "C:\Users\Administrator\Desktop\Release.1.0.0\main.py", line 216, in load_cache
    difficulties = [file[6:-5] for file in os.listdir(os.path.join('./Assets/Tracks', self.song_id.get())) if
                                          
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: './Assets/Tracks\\Shadow.SumaiLightvs姜米條.0'

**Comment by ClankySun10936** [comment]
已修复
