### ISSUE TITLE
卡在解包

### ISSUE THREAD

**Issue by Walkersifolia** [ClankySun10936/Phigros-Autoplay-Script#7]
一直卡在解包，控制台也没有任何报错
![S@J) I~US70{JV}_Q13YG1R](https://github.com/ClankySun10936/Phigros-Autoplay-Script/assets/129571444/a3af98dc-517d-4f04-86e4-74fe37ef5a9e)
使用的是pycharm运行

**Comment by ZiHengPlazy** [comment]
+1，解包解了三个小时

**Comment by Walkersifolia** [comment]
> +1，解包解了三个小时

最新版的没有问题了喔，git pull更新到最新的代码即可，如果还是不行就是电脑性能问题
